

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Setup uv
        uses: yezz123/setup-uv@v4

      - name: Build Wheels
        run: uvx --from build pyproject-build --installer uv

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: fast_data_loader
          path: ./dist/*.whl
